##############################
# Etapa 1: Build (compilação) #
##############################
FROM maven:3.8.6-openjdk-11 AS build

COPY pom.xml ./
COPY .mvn .mvn
COPY src src

RUN mvn clean install

FROM maven:3.8.6-openjdk-11

WORKDIR /app
COPY --from=build target/*.jar app.jar

# Expõe as portas da aplicação e a porta de debug remoto
EXPOSE 8080 5005

# Executa o jar com suporte a debug remoto e perfil ativo (DEV por padrão)
ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE:-DEV}", "-jar", "app.jar"]
