version: "3.7"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: base_consulta_credito
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      JAVA_OPTS: "-Xms768m -Xmx768m"
      SPRING_PROFILES_ACTIVE: DEV
      SERVER_PORT: 8080
      TIMEOUT_REQUEST: 4000
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
